remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Adrian Kirkeby
logo: div/profile.JPG
description: >
  Researcher in Inverse Problems <br><br>
  [🏠 Home](/) <br>
  [📚 Publications](/publications) <br>
show_downloads: false

